services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./config:/app/config
    depends_on:
      - redis
      - postgres
  redis:
    image: docker.io/redis:alpine
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
  adminer:
    image: docker.io/adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
